group=io.papermc.paper
version=26.1.2-R0.1-SNAPSHOT
mcVersion=26.1.2
# This is the current API version for use in (paper-)plugin.yml files
# During snapshot cycles this should be the anticipated version of the release target
apiVersion=26.1.2
channel=STABLE

# Set to true while updating Minecraft version
updatingMinecraft=false

# Paper 26.1.2 main branch commit
paperRef=34cf3ab0f9532d2671319ff8c4ac55b91bb66d77

org.gradle.configuration-cache=true
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.vfs.watch=false
